title: Amanda Lee # your name (or website title) here
logo: "/images/amanda_lee.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Amanda is a data analyst with a strong proficiency in Python, SQL and Tableau. The years of studies in NUS has allowed her to build a strong and solid foundation of knowledge in science and research. She is looking for a role as a data analyst, bringing actionable and innovative solutions to your organisation.
  <br><br>
  **Skills**
  <br><br>
  Microsoft Excel
  <br><br>Big Data (Spark)
  <br><br>MySQL/Tableau
  <br><br>Data Analysis
  <br><br>Machine Learning Model (TensorFlow) 
  <br><br>Deep Learning (Neural Network) 
  <br><br>
  <a href="https://www.linkedin.com/in/amandaleejl/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
